// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwcPBStTwaO3N0fIacbHnApbZw8ZhjEjM',
    appId: '1:51733160680:web:db9067803bd5983d861f5d',
    messagingSenderId: '51733160680',
    projectId: 'invoice-marker',
    authDomain: 'invoice-marker.firebaseapp.com',
    storageBucket: 'invoice-marker.firebasestorage.app',
    measurementId: 'G-E6Q98E78HZ',
    databaseURL: 'https://invoice-marker.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwcPBStTwaO3N0fIacbHnApbZw8ZhjEjM',
    appId: '1:51733160680:android:1db1b0227a780b6b861f5d',
    messagingSenderId: '51733160680',
    projectId: 'invoice-marker',
    storageBucket: 'invoice-marker.firebasestorage.app',
    databaseURL: 'https://invoice-marker.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwcPBStTwaO3N0fIacbHnApbZw8ZhjEjM',
    appId: '1:51733160680:ios:877d19fee3e90108861f5d',
    messagingSenderId: '51733160680',
    projectId: 'invoice-marker',
    storageBucket: 'invoice-marker.firebasestorage.app',
    iosBundleId: 'billora',
    databaseURL: 'https://invoice-marker.firebaseio.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwcPBStTwaO3N0fIacbHnApbZw8ZhjEjM',
    appId: '1:51733160680:ios:877d19fee3e90108861f5d',
    messagingSenderId: '51733160680',
    projectId: 'invoice-marker',
    storageBucket: 'invoice-marker.firebasestorage.app',
    iosBundleId: 'billora',
    databaseURL: 'https://invoice-marker.firebaseio.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwcPBStTwaO3N0fIacbHnApbZw8ZhjEjM',
    appId: '1:51733160680:web:db9067803bd5983d861f5d',
    messagingSenderId: '51733160680',
    projectId: 'invoice-marker',
    authDomain: 'invoice-marker.firebaseapp.com',
    storageBucket: 'invoice-marker.firebasestorage.app',
    measurementId: 'G-E6Q98E78HZ',
    databaseURL: 'https://invoice-marker.firebaseio.com',
  );

}
