// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCav9xXYxTZChKpX8B3lAu51PkPCAUtPmk',
    appId: '1:1018575120402:web:3c10646dd3b3ed3cd190cb',
    messagingSenderId: '1018575120402',
    projectId: 'billora-invoice-maker',
    authDomain: 'billora-invoice-maker.firebaseapp.com',
    storageBucket: 'billora-invoice-maker.firebasestorage.app',
    measurementId: 'G-MXY3Y64C5L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBceKMe6jFiD9TuuRogHv2EqMPXtPP3KE4',
    appId: '1:1018575120402:android:a0c31a6d5a51630fd190cb',
    messagingSenderId: '1018575120402',
    projectId: 'billora-invoice-maker',
    storageBucket: 'billora-invoice-maker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi4mYkGbyzFvlOtAPHi1FraaQoerLlLvY',
    appId: '1:1018575120402:ios:3806aa2780e0152bd190cb',
    messagingSenderId: '1018575120402',
    projectId: 'billora-invoice-maker',
    storageBucket: 'billora-invoice-maker.firebasestorage.app',
    iosBundleId: 'com.example.billora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi4mYkGbyzFvlOtAPHi1FraaQoerLlLvY',
    appId: '1:1018575120402:ios:3806aa2780e0152bd190cb',
    messagingSenderId: '1018575120402',
    projectId: 'billora-invoice-maker',
    storageBucket: 'billora-invoice-maker.firebasestorage.app',
    iosBundleId: 'com.example.billora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCav9xXYxTZChKpX8B3lAu51PkPCAUtPmk',
    appId: '1:1018575120402:web:437e83eabe88956ed190cb',
    messagingSenderId: '1018575120402',
    projectId: 'billora-invoice-maker',
    authDomain: 'billora-invoice-maker.firebaseapp.com',
    storageBucket: 'billora-invoice-maker.firebasestorage.app',
    measurementId: 'G-F8LK4ERNB4',
  );

}
