name: billora
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  dartz: ^0.10.1
  get_it: ^8.0.3
  injectable: ^2.5.0
  freezed_annotation: ^2.4.1  # Downgrade to stable version
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  firebase_storage: ^12.4.9
  # flutterfire_cli: ^1.3.1
  flutter_bloc: ^8.1.6
  json_annotation: ^4.9.0
  flutter_localizations:
    sdk: flutter
  intl: any
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.5.4
  freezed: ^2.5.8
  json_serializable: ^6.9.5
  injectable_generator: ^2.7.0
  mockito: ^5.4.2
  mocktail: ^0.3.0
  flutter_flavorizr: ^2.2.1

flutter:
  generate: true
  assets:
    - assets/icons/google.png

flutter_flavorizr:
  app:
    android:
      flavorDimensions: [env]
      flavors:
        dev:
          applicationId: "com.Billora.invoice_maker.dev"
          name: "Billora Dev"
        prod:
          applicationId: "com.Billora.invoice_maker"
          name: "Billora"
    ios:
      flavors:
        dev:
          bundleId: "com.Billora.invoiceMaker.dev"
          name: "Billora Dev"
        prod:
          bundleId: "com.Billora.invoiceMaker"
          name: "Billora"
  