name: billora
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  dartz: ^0.10.1
  get_it: ^8.0.3
  injectable: ^2.5.0
  freezed_annotation: ^2.4.1  # Downgrade to stable version
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  firebase_storage: ^12.4.9
  cloud_functions: ^5.6.1
  # flutterfire_cli: ^1.3.1
  flutter_bloc: ^8.1.6
  provider: ^6.1.2
  json_annotation: ^4.9.0
  intl: ^0.19.0

  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.1
  pdf: ^3.11.3
  printing: ^5.14.2
  http: ^1.2.1
  flutter_dotenv: ^5.1.0
  
  # Bill Scanner Dependencies
  # google_mlkit_text_recognition: ^0.13.0  # Temporarily disabled due to compatibility issues
  # camera: ^0.11.0+4  # Temporarily disabled due to compatibility issues
  image: ^4.1.7
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  # permission_handler: ^11.3.0  # Temporarily disabled due to compatibility issues
  lottie: ^3.1.0
  shimmer: ^3.0.0
  file_picker: ^8.0.0

  # Week 7 - Smart Suggestions & Tags System
  equatable: ^2.0.5
  sqflite: ^2.3.3+1
  shared_preferences: ^2.3.2
  uuid: ^4.5.1
  flutter_typeahead: ^5.2.0
  flutter_tags_x: ^1.1.0

  # Week 8 - Dashboard & Excel Reporting
  syncfusion_flutter_charts: ^30.1.42
  excel: ^2.1.0
  dio_cache_interceptor: ^4.0.0
  sentry_flutter: ^9.0.0
  chips_choice: ^3.0.1
  fl_chart: ^0.68.0
  dropdown_button2: ^2.3.9

  # Week 9 - AI & QR Code Integration
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.5.4
  freezed: ^2.5.8
  json_serializable: ^6.9.5
  injectable_generator: ^2.7.0
  mockito: ^5.4.2
  mocktail: ^0.3.0
  flutter_flavorizr: ^2.2.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/images/templates/
    - .env

flutter_gen:
  synthetic-package: false

flutter_flavorizr:
  app:
    android:
      flavorDimensions: [env]
      flavors:
        dev:
          applicationId: "com.Billora.invoice_maker.dev"
          name: "Billora Dev"
        prod:
          applicationId: "com.Billora.invoice_maker"
          name: "Billora"
    ios:
      flavors:
        dev:
          bundleId: "com.Billora.invoiceMaker.dev"
          name: "Billora Dev"
        prod:
          bundleId: "com.Billora.invoiceMaker"
          name: "Billora"
  