// Mocks generated by Mockito 5.4.6 from annotations
// in billora/test/features/bill_scanner/domain/usecases/scan_bill_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:billora/src/core/errors/failures.dart' as _i5;
import 'package:billora/src/features/bill_scanner/domain/entities/scan_result.dart'
    as _i6;
import 'package:billora/src/features/bill_scanner/domain/entities/scanned_bill.dart'
    as _i7;
import 'package:billora/src/features/bill_scanner/domain/repositories/bill_scanner_repository.dart'
    as _i3;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BillScannerRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBillScannerRepository extends _i1.Mock
    implements _i3.BillScannerRepository {
  MockBillScannerRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ScanResult>> scanBill(
    String? imagePath,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#scanBill, [imagePath]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.ScanResult>>.value(
                  _FakeEither_0<_i5.Failure, _i6.ScanResult>(
                    this,
                    Invocation.method(#scanBill, [imagePath]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.ScanResult>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.ScannedBill>> extractBillData(
    String? imagePath,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#extractBillData, [imagePath]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i7.ScannedBill>>.value(
                  _FakeEither_0<_i5.Failure, _i7.ScannedBill>(
                    this,
                    Invocation.method(#extractBillData, [imagePath]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i7.ScannedBill>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.ScannedBill>> validateBillData(
    _i7.ScannedBill? bill,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#validateBillData, [bill]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i7.ScannedBill>>.value(
                  _FakeEither_0<_i5.Failure, _i7.ScannedBill>(
                    this,
                    Invocation.method(#validateBillData, [bill]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i7.ScannedBill>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> processWithRegex(
    String? rawText,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#processWithRegex, [rawText]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
              _FakeEither_0<_i5.Failure, String>(
                this,
                Invocation.method(#processWithRegex, [rawText]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, String>>);
}
